# GET http://localhost:8000/api/csrf/restore

//get all spots
# GET http://localhost:8000/api/spots

// get spot by id
# GET http://localhost:8000/api/spots/1

//get all reviews by a spot based on id
# GET http://localhost:8000/api/spots/1/reviews

# DELETE http://localhost:8000/api/spots/1

GET http://localhost:8000/api/spots/1/test

// didn't work - sign up
# POST http://localhost:8000/api/users
# Content-Type: application/json
# # XSRF-TOKEN: "Qe3CssjT-1Y92SpqXW28Ql_btq2ukzE9S5Js"
# {
#     "firstName": "Black",
#     "lastName": "Adam",
#     "email": "TheRock@gmail.com",
#     "username": "BlackAdam",
#     "password": "password",
# }

# POST http://localhost:8000/api/users/login
# Content-Type: application/json

# {
#     "credential": "BlackAdam",
#     "password": "password"
# }
